stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: ArtifactBuild
      displayName: Build and Push Artifact
      pool:
        inputs:
          pollingTimeoutSec: '300'
        vmImage: ubuntu-latest
      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish pipeline artifact
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: '$(Artifact.Name)'
          publishLocation: 'pipeline'
