trigger:
  - staging

variables:
  - group: npm-vars
  - template: templates/var.yaml
  - template: templates/staging-var.yaml

stages:
  - template: templates/build.yaml
  - template: templates/deployment.yaml
